### PR TITLE
Add internationalization support for Español y Português

### PR DESCRIPTION
**Pull request by ghost**
For this international conference, we want to have the conference information available in different languages. This PR adds the first step in internationalization support. Running the site on localhost (`hugo server --config=hugo.toml`) the `/pt/` and `/es/` paths are now in their respective languages.

Translation by file name, [as described in the Hugo docs here](https://gohugo.io/content-management/multilingual/#translation-by-file-name), is the chosen method for implementing internationalization, due to the simplicity in internationalizing page slugs as opposed to by content directory.

Things done:
- Activated pt-BR and es-AR internationalization
  - Added language metadata and menu item translations
  - Duplicated English language content into placeholder files for later filling in with translations
    - Each page (ie `about.md`) now has `about.es.md` and `about.pt.md` for español y português, respectively
  - Updated slugs in placeholder español and português where the slugs differ from English language
- Fixed template image `src` not being the absolute url, which broke those images in internationalization.

Still to do:
- Double check menu translations in `hugo.toml`
- There are many pages referenced in the menu, and in other pages, which do not yet exist, and are broken. `Branding` for example. This pages need to be created.
- Implement a button somewhere allowing for changing language
- Detect browser language and redirect to user's language automatically (this will be hard with Hugo)

Pages that still need to be created:
- `branding`
- `diversity-and-inclusion`
- `registration`
- `B2B`
- `call-for-papers`
- `pricing`
- `register`
- `workshops`
- `stay`
- `program`
- `events`
- `about`

### CODE REVIEW

**Comment by FelipeSBarros** [comment]
@rami-dv grwat job! I was checking the changes you done I as I understand the webpage will identify my "lenguage profile" and use the according language, right?
Don't you think worth adding [a laguage switcher](https://dev.to/feministclickback/how-to-add-a-language-switcher-to-your-hugo-site-2oh6)?

**Review by FelipeSBarros — APPROVED** [review]
All good. Just confirm if woth adding a langiage switcher and merge.

**Comment by ghost** [comment]
Hey @FelipeSBarros ! The page doesn't currently identify the web browser language and redirect accordingly, or include a language switcher. These are both planned features for a separate PR

**Comment by FelipeSBarros** [comment]
> Hey @FelipeSBarros ! The page doesn't currently identify the web browser language and redirect accordingly, or include a language switcher. These are both planned features for a separate PR

Great, @rami-dv !!

**Pull request merged**
